"""Default non-secret ForgeX settings and schema."""

from __future__ import annotations

from typing import Any


SETTINGS_DEFAULTS: dict[str, Any] = {
    "general.startup_behavior": "open_last_workspace",
    "general.default_project_mode": "generate_into_open_folder",
    "general.confirm_before_flash": True,
    "general.auto_open_generated_main_cpp": True,
    "appearance.theme": "forgex-dark",
    "appearance.accent": "purple",
    "appearance.font_size": 14,
    "appearance.ui_density": "comfortable",
    "appearance.panel_borders": True,
    "appearance.motion": "subtle",
    "appearance.terminal_font_size": 13,
    "appearance.background_asset_id": "",
    "appearance.background_asset_name": "",
    "appearance.background_dim": 72,
    "appearance.background_blur": 0,
    "appearance.background_fit": "cover",
    "appearance.background_position": "center",
    "appearance.surface_opacity": 94,
    "appearance.contrast": "standard",
    "appearance.corner_radius": 10,
    "appearance.glow_intensity": 35,
    "editor.font_size": 14,
    "editor.tab_size": 2,
    "editor.word_wrap": True,
    "editor.minimap_enabled": False,
    "editor.auto_save": False,
    "editor.format_on_save": False,
    "editor.show_breadcrumbs": True,
    "editor.show_line_numbers": True,
    "terminal.font_size": 13,
    "terminal.scrollback_lines": 1000,
    "terminal.clear_output_before_build": False,
    "terminal.show_timestamps": True,
    "terminal.default_tab": "Output",
    "terminal.serial_baud_default": 115200,
    "workspace.remember_last_workspace": True,
    "workspace.recent_project_limit": 10,
    "workspace.excluded_folders": [".git", ".pio", "node_modules", "build", "dist"],
    "workspace.confirm_before_delete": True,
    "workspace.auto_refresh_explorer": True,
    "workspace.show_hidden_files": False,
    "hardware.default_board": "esp32dev",
    "hardware.default_framework": "PlatformIO",
    "hardware.default_upload_speed": 921600,
    "hardware.default_monitor_speed": 115200,
    "hardware.auto_detect_devices": True,
    "hardware.refresh_devices_interval": 5,
    "hardware.confirm_before_flash": True,
    "hardware.confirm_before_erase": True,
    "hardware.confirm_before_reset": True,
    "hardware.confirm_before_debug_attach": True,
    "security.mask_api_keys": True,
    "security.hardware_approval_strict_mode": True,
}


SETTINGS_SCHEMA: dict[str, dict[str, Any]] = {
    "general.startup_behavior": {
        "type": "select",
        "label": "Startup behavior",
        "category": "general",
        "options": ["open_last_workspace", "show_welcome_screen", "open_empty_workspace"],
    },
    "general.default_project_mode": {
        "type": "select",
        "label": "Default project mode",
        "category": "general",
        "options": ["generate_into_open_folder", "new_project", "modify_existing_project"],
    },
    "general.confirm_before_flash": {"type": "boolean", "label": "Confirm before flash", "category": "general"},
    "general.auto_open_generated_main_cpp": {
        "type": "boolean",
        "label": "Auto-open generated main.cpp",
        "category": "general",
    },
    "appearance.theme": {
        "type": "select",
        "label": "Theme",
        "category": "appearance",
        "options": ["forgex-dark", "forgex-midnight", "obsidian", "graphite", "nord", "solarized-dark", "porcelain", "paper", "dawn", "solarized-light", "high-contrast-dark", "high-contrast-light", "light", "system"],
    },
    "appearance.accent": {
        "type": "select",
        "label": "Accent color",
        "category": "appearance",
        "options": ["purple", "blue", "cyan", "green", "amber", "orange", "rose", "neutral"],
    },
    "appearance.font_size": {"type": "number", "label": "Font size", "category": "appearance", "min": 12, "max": 18},
    "appearance.ui_density": {
        "type": "select",
        "label": "UI density",
        "category": "appearance",
        "options": ["compact", "comfortable"],
    },
    "appearance.panel_borders": {"type": "boolean", "label": "Panel borders", "category": "appearance"},
    "appearance.motion": {
        "type": "select",
        "label": "Interface motion",
        "category": "appearance",
        "options": ["full", "subtle", "off"],
    },
    "appearance.terminal_font_size": {
        "type": "number",
        "label": "Terminal font size",
        "category": "appearance",
        "min": 11,
        "max": 18,
    },
    "appearance.background_asset_id": {
        "type": "string",
        "label": "Background asset ID",
        "category": "appearance",
        "max_length": 64,
        "pattern": r"(?:|background-[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.(?:png|jpg|webp))",
    },
    "appearance.background_asset_name": {
        "type": "string",
        "label": "Background image name",
        "category": "appearance",
        "max_length": 255,
    },
    "appearance.background_dim": {
        "type": "number",
        "label": "Background dimming",
        "category": "appearance",
        "min": 0,
        "max": 100,
    },
    "appearance.background_blur": {
        "type": "number",
        "label": "Background blur",
        "category": "appearance",
        "min": 0,
        "max": 30,
    },
    "appearance.background_fit": {
        "type": "select",
        "label": "Background fit",
        "category": "appearance",
        "options": ["cover", "contain", "fill"],
    },
    "appearance.background_position": {
        "type": "select",
        "label": "Background position",
        "category": "appearance",
        "options": ["center", "top", "bottom", "left", "right"],
    },
    "appearance.surface_opacity": {
        "type": "number",
        "label": "Surface opacity",
        "category": "appearance",
        "min": 65,
        "max": 100,
    },
    "appearance.contrast": {
        "type": "select",
        "label": "Interface contrast",
        "category": "appearance",
        "options": ["soft", "standard", "high"],
    },
    "appearance.corner_radius": {
        "type": "number",
        "label": "Corner radius",
        "category": "appearance",
        "min": 0,
        "max": 20,
    },
    "appearance.glow_intensity": {
        "type": "number",
        "label": "Glow intensity",
        "category": "appearance",
        "min": 0,
        "max": 100,
    },
    "editor.font_size": {"type": "number", "label": "Font size", "category": "editor", "min": 11, "max": 22},
    "editor.tab_size": {"type": "number", "label": "Tab size", "category": "editor", "min": 2, "max": 8},
    "editor.word_wrap": {"type": "boolean", "label": "Word wrap", "category": "editor"},
    "editor.minimap_enabled": {"type": "boolean", "label": "Minimap", "category": "editor"},
    "editor.auto_save": {"type": "boolean", "label": "Auto save", "category": "editor"},
    "editor.format_on_save": {"type": "boolean", "label": "Format on save", "category": "editor"},
    "editor.show_breadcrumbs": {"type": "boolean", "label": "Breadcrumbs", "category": "editor"},
    "editor.show_line_numbers": {"type": "boolean", "label": "Line numbers", "category": "editor"},
    "terminal.font_size": {"type": "number", "label": "Terminal font size", "category": "terminal", "min": 11, "max": 22},
    "terminal.scrollback_lines": {"type": "number", "label": "Scrollback lines", "category": "terminal", "min": 200, "max": 20000},
    "terminal.clear_output_before_build": {
        "type": "boolean",
        "label": "Clear output before build",
        "category": "terminal",
    },
    "terminal.show_timestamps": {"type": "boolean", "label": "Show timestamps", "category": "terminal"},
    "terminal.default_tab": {
        "type": "select",
        "label": "Default terminal tab",
        "category": "terminal",
        "options": ["Output", "Terminal", "Serial Monitor"],
    },
    "terminal.serial_baud_default": {
        "type": "number",
        "label": "Default serial baud",
        "category": "terminal",
        "min": 300,
        "max": 2000000,
    },
    "workspace.remember_last_workspace": {
        "type": "boolean",
        "label": "Remember last workspace",
        "category": "workspace",
    },
    "workspace.recent_project_limit": {
        "type": "number",
        "label": "Recent project limit",
        "category": "workspace",
        "min": 1,
        "max": 50,
    },
    "workspace.excluded_folders": {"type": "string_list", "label": "Excluded folders", "category": "workspace"},
    "workspace.confirm_before_delete": {"type": "boolean", "label": "Confirm before delete", "category": "workspace"},
    "workspace.auto_refresh_explorer": {"type": "boolean", "label": "Auto-refresh explorer", "category": "workspace"},
    "workspace.show_hidden_files": {"type": "boolean", "label": "Show hidden files", "category": "workspace"},
    "hardware.default_board": {"type": "string", "label": "Default board", "category": "hardware"},
    "hardware.default_framework": {
        "type": "select",
        "label": "Default framework",
        "category": "hardware",
        "options": ["PlatformIO", "Arduino", "ESP-IDF"],
    },
    "hardware.default_upload_speed": {
        "type": "number",
        "label": "Default upload speed",
        "category": "hardware",
        "min": 9600,
        "max": 2000000,
    },
    "hardware.default_monitor_speed": {
        "type": "number",
        "label": "Default monitor speed",
        "category": "hardware",
        "min": 300,
        "max": 2000000,
    },
    "hardware.auto_detect_devices": {"type": "boolean", "label": "Auto-detect devices", "category": "hardware"},
    "hardware.refresh_devices_interval": {
        "type": "number",
        "label": "Device refresh interval",
        "category": "hardware",
        "min": 2,
        "max": 120,
    },
    "hardware.confirm_before_flash": {"type": "boolean", "label": "Confirm before flash", "category": "hardware"},
    "hardware.confirm_before_erase": {"type": "boolean", "label": "Confirm before erase", "category": "hardware"},
    "hardware.confirm_before_reset": {"type": "boolean", "label": "Confirm before reset", "category": "hardware"},
    "hardware.confirm_before_debug_attach": {
        "type": "boolean",
        "label": "Confirm before debug attach",
        "category": "hardware",
    },
    "security.mask_api_keys": {"type": "boolean", "label": "Mask API keys", "category": "security"},
    "security.hardware_approval_strict_mode": {
        "type": "boolean",
        "label": "Hardware approval strict mode",
        "category": "security",
    },
}

for key, default in SETTINGS_DEFAULTS.items():
    SETTINGS_SCHEMA[key]["default"] = default
