"""Execution WebSocket schemas."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import Field

from .common import APIModel


class ExecutionEventType(str, Enum):
    TASK_CREATED = "TASK_CREATED"
    PLAN_GENERATED = "PLAN_GENERATED"
    PLAN_FAILED = "PLAN_FAILED"
    CODE_GENERATION_STARTED = "CODE_GENERATION_STARTED"
    CODE_GENERATION_COMPLETED = "CODE_GENERATION_COMPLETED"
    CODE_GENERATION_FAILED = "CODE_GENERATION_FAILED"
    GENERATION_STRATEGY_SELECTED = "GENERATION_STRATEGY_SELECTED"
    GENERATION_STARTED = "GENERATION_STARTED"
    GENERATION_FAILED = "GENERATION_FAILED"
    REQUIREMENTS_EXTRACTION_STARTED = "REQUIREMENTS_EXTRACTION_STARTED"
    REQUIREMENTS_EXTRACTED = "REQUIREMENTS_EXTRACTED"
    MANIFEST_GENERATION_STARTED = "MANIFEST_GENERATION_STARTED"
    MANIFEST_CREATED = "MANIFEST_CREATED"
    FILE_GENERATION_STARTED = "FILE_GENERATION_STARTED"
    FILE_GENERATION_REPAIR_STARTED = "FILE_GENERATION_REPAIR_STARTED"
    FILE_GENERATION_FALLBACK_STARTED = "FILE_GENERATION_FALLBACK_STARTED"
    FILE_GENERATION_VALIDATED = "FILE_GENERATION_VALIDATED"
    FILE_WRITTEN = "FILE_WRITTEN"
    FILE_FAILED = "FILE_FAILED"
    GENERATION_INCOMPLETE = "GENERATION_INCOMPLETE"
    GENERATION_COMPLETED = "GENERATION_COMPLETED"
    BUILD_BLOCKED = "BUILD_BLOCKED"
    BUILD_STARTED = "BUILD_STARTED"
    BUILD_COMPLETED = "BUILD_COMPLETED"
    BUILD_FAILED = "BUILD_FAILED"
    BUILD_REPAIR_STARTED = "BUILD_REPAIR_STARTED"
    BUILD_REPAIR_COMPLETED = "BUILD_REPAIR_COMPLETED"
    BUILD_REPAIR_FAILED = "BUILD_REPAIR_FAILED"
    FLASH_STARTED = "FLASH_STARTED"
    FLASH_COMPLETED = "FLASH_COMPLETED"
    FLASH_FAILED = "FLASH_FAILED"
    MONITOR_STARTED = "MONITOR_STARTED"
    MONITOR_COMPLETED = "MONITOR_COMPLETED"
    MONITOR_FAILED = "MONITOR_FAILED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    WORKFLOW_CANCELLED = "WORKFLOW_CANCELLED"


class ExecutionEvent(APIModel):
    sequence: int = Field(ge=1)
    event: ExecutionEventType
    timestamp: datetime
    task_id: str
    execution_id: str
    workflow_correlation_id: str
    payload: dict[str, Any] = Field(default_factory=dict)
